### ISSUE TITLE
Don't need to copy code

### ISSUE THREAD

**Issue by lizmat** [ajs/perl6-Operator-Listcat#1]
https://github.com/ajs/perl6-Operator-Listcat/blob/f4b579affcef62e62774a3d602db9dadd7f971b4/lib/Operator/Listcat.pm6#L10

can be written as:

    my constant &infix:<< ⊕ >> is export = &infix:<listcat>;

**Comment by ajs** [comment]
Ah, I tried using := and it didn't get exported. I'll try without the aliasing.

**Comment by ajs** [comment]
Nope. It fails with:

```
tests/listcat.t
===SORRY!=== Error while compiling /home/ajs/src/perl6-Operator-Listcat/tests/listcat.t
Confused
at /home/ajs/src/perl6-Operator-Listcat/tests/listcat.t:5
------> cmp-ok <1 2 3>⏏ ⊕ <a b c>, '~~', <1 2 3 a b c>, "Simple
    expecting any of:
        infix
        infix stopper
        postfix
        statement end
        statement modifier
        statement modifier loop
```

Which I take to indicate that the operator wasn't exported.

I cut-and-paste your definition exactly, but it is more or less the same (except for `constant` and aliasing) as what I was doing before.

Should I submit this as a rakudo bug?

**Comment by lizmat** [comment]
See https://github.com/ajs/perl6-Operator-Listcat/pull/2 . Seems it's sensitive to the delimiter being used and spacing.  So yes, worthy of a Rakudo bug report.

**Comment by ajs** [comment]
Closed this as it's being handled in rakudo and I have a local workaround.
